# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/model.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frpc/model.proto\"&\n\x03img\x12\x0e\n\x06indata\x18\x01 \x03(\t\x12\x0f\n\x07img_num\x18\x02 \x01(\x05\"\x19\n\x06vector\x12\x0f\n\x07outdata\x18\x01 \x03(\x02\x32\x1f\n\x05Model\x12\x16\n\x03mod\x12\x04.img\x1a\x07.vector\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc.model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMG']._serialized_start=19
  _globals['_IMG']._serialized_end=57
  _globals['_VECTOR']._serialized_start=59
  _globals['_VECTOR']._serialized_end=84
  _globals['_MODEL']._serialized_start=86
  _globals['_MODEL']._serialized_end=117
# @@protoc_insertion_point(module_scope)
